### ISSUE TITLE
Scrapli fall down with timeout error even though timeouts are increased. 

### ISSUE THREAD

**Issue by artyomovs** [carlmontanari/scrapli#29] opened 2020-07-06 16:18 UTC
Hello.
**Describe the bug**
When I perform a long-term operation, scapli fails with the timeout exception. But the timers are increased

**To Reproduce**
`
def test_scrapli():]
    my_device = {
        "host": "X.X.X.X",
        "auth_username": "username",
        "auth_password": "password",
        "auth_strict_key": False,
        'port': 22,
        'timeout_ops': 120,
        'timeout_socket': 120,
        'timeout_transport': 120,
        'timeout_exit': False,   
        'ssh_config_file': False,               
    }    
    conn = IOSXEDriver(**my_device)
    conn.open()
    response = conn.send_command("cellular 0 lte sim activate slot 0")
    print(response.result)
`

**Screenshots**
![screen](https://user-images.githubusercontent.com/4401664/86615656-6ad09480-bfbd-11ea-9ac4-547891554b43.png)

**OS (please complete the following information):**
 - OS: Linux Ubuntu 18
 - scrapli version: scrapli==2020.7.4
 - version of any optional extras (paramiko|ssh2-python|textfsm, etc.): scrapli-ssh2==2020.6.6

**Additional context**
[logs.txt](https://github.com/carlmontanari/scrapli/files/4880099/logs.txt)

**Comment by carlmontanari** [comment] 2020-07-06 16:59
Hey @artyomovs -- thanks for raising this!

I've just done some testing about timeouts for system and ssh2 transports -- I added a sleep in `send_inputs` to simulate a really long running command (sleep 75seconds) and was unable to reproduce this. 

Can you post the output of this when ran normally on terminal? Does it change the prompt or anything like that -- I don't think this is the issue, but just want to clarify?

From the logs it looks like scrapli is timing out in exactly 10 seconds which is a bit strange -- is it possible you have an older version of scrapli installed? The reason I ask is that the `timeout_ops` value used to be 10 seconds in some earlier versions of scrapli, so that could explain some of this behavior -- especially if there was an older bug where I had not gotten the values set appropriately :)

To just confirm could you get the output of:

`python -m pip list | grep scrapli` from whatever shell/env you run this from?

Also would it be possible to print the timeout values in our script prior to sending that command just so we can confirm they are getting set correctly?

```
print(conn.channel.timeout_ops)
```

With that info I can hopefully dig into this a bit more this evening so we can get this sorted out for you!

Thanks for raising the issue and providing logs and all that good stuff!

Carl

**Comment by artyomovs** [comment] 2020-07-06 17:50
Hi @carlmontanari . Thanks for the instant response. 
I'll try to cover all your questions: 
1. The prompt is the same. I can run this command via terminal. Please, check GIF. 
![30KKdCDYXQ](https://user-images.githubusercontent.com/4401664/86623314-0b2cb600-bfca-11ea-9491-2035b77d60d6.gif)
2. scrapli pips versions:
nornir-scrapli (2020.4.11)
scrapli (2020.7.4)
scrapli-ssh2 (2020.6.6)
3. The print(conn.channel.timeout_ops) gives 120 (exactly the timeout that I set).

**Comment by carlmontanari** [comment] 2020-07-06 23:55
@artyomovs I've got some good news and some bad news!

I'll start with the bad: this is embarrassing :D this was a pretty silly bug. What was happening was at some point I had decided it would be a good idea to set the timeout to a small value (10s) when "getting" the prompt. This by itself was probably ok (though in hind sight I don't like this because it was transparent to the user so thats probably a bad thing in general), however what was ending up happening was the timeout value in the underlying transport object was getting updated with this 10s value.... overriding what the user has provided. Not good!

The good news! This is fixed in develop! I just removed the timeout setting that was happening in `get_prompt` -- I think it was a bad idea anyway, and other than not breaking things it should have no impact on any users! Also good news -- thank you very much for the second issue you've helped identify and solve!! I really appreciate the helpful issues with logs and good details and all of that stuff, its really great!

If you wouldn't mind testing develop to make sure this is fixed for you I may just go ahead and merge to master and push a new release to pypi since this is a pretty silly bug to leave floating around :) 

Thanks!

Carl

**Comment by artyomovs** [comment] 2020-07-07 09:00
Hi @carlmontanari . 
That's a good news:) 
I would be happy to test if your fix solved this issue. Please, give me instructions for that.

**Comment by carlmontanari** [comment] 2020-07-07 13:20
Sorry about that! You can install the develop branch like so:

```
pip install -e git+https://github.com/carlmontanari/scrapli.git@develop#egg=scrapli
```

That should be all you need to do, then it *should* work :) 

Carl

**Comment by artyomovs** [comment] 2020-07-07 14:47
@carlmontanari 
Checked it. Works perfect. Script is waiting for prompt as expected. 
Thank you very much for your lib and fast response:)

**Comment by carlmontanari** [comment] 2020-07-07 15:03
Awesome, thank you for confirming! I'll go ahead and close this and hopefully push to PyPI later today/tomorrow. 

Thanks again for reporting this and working through it with me!

**Closed by carlmontanari** 2020-07-07 15:03 UTC
Labels: bug
