### ISSUE TITLE
`on_close` callbacks are not called on timeout

### ISSUE THREAD

**Issue by erwinkinn** [carlmontanari/scrapli#285] opened 2023-04-28 11:56 UTC
**Hello :)**
The bug (at least I treat this as a bug) is when I got timed out, I see my on_close callback is not called at all. 
At the same time the connection is closed [here](https://github.com/carlmontanari/scrapli/blob/b34d83ae53e8c243626ff94402bd439a523cc968/scrapli/decorators.py#L133).
I understand that this is an exceptional case, but scrapli closes the connection with its own hands when getting a timeout, so why not call a callback?
I think the bugfix appears to be not a trivial one.  This is not just a try-cache ScrapliTimeout with  further call of on_close, because on_close is normally called **before** closing the connection. And `_handle_timeout` function closes it inplace.
May be we could pass the reference to a callback deeper to the channel object? At least channel object is accessible from _handle_timeout function? If this idea looks good to you, I could make a merge request. 

**To Reproduce**
My script is smth like this:
```python
from scrapli import AsyncScrapli
async def test_this():
    async def on_open_callback(driver: AsyncScrapli):
        print("OPEN")

    async def on_close_callback(driver: AsyncScrapli):
        print("CLOSE")

    with _local_repo():
        driver = AsyncScrapli(
            platform="my_linux_platform",
            host=...,
            port=22,
            transport="asyncssh",
            auth_username=...,
            auth_password=...,
            auth_strict_key=False,
            on_open=on_open_callback,
            on_close=on_close_callback,
        )
        await driver.open()  # <-- Here I see "OPEN" 
        res = await driver.send_command("cat", timeout_ops=3)
        # ScrapliTimeout exception here
```
2. The above example is not a copy-paste one, sorry. I use my local `scrapli_community` module to appease scrapli platforms lookup mechanics. My platform is just an ordinary Ubuntu 20.04

**Expected behavior**

When timeout occurred I expect scrapli to call on_close callback right before closing the transport.

**OS (please complete the following information):**
 - OS: Windows 10
 - scrapli version is the latest

**Comment by carlmontanari** [comment] 2023-04-28 23:58
hey @erwinkinn and @rlad78 

interesting. @erwinkinn is your use case here similar to what @rlad78 mentioned in @284? my initial reaction is kind of a "not broke wont fix" -- the reason I say that is that the *usual* assumption for time outs would be either:

1) the connection is dead in which case the on close would never really work or 
2) you handle a timeout then do whatever you want

My assumption/expectation has always been that the on open/close things exist for you to do things like disable paging, gracefully close connections, or other things that are directly scrapli/connection related.

as you mentioned this is obviously not a super quick/easy change. im also not convinced (but am open to being convinced!) that this is something I would want to support/change. 

I think way way way way long ago there was a driver option that you could set that would prevent scrapli from closing the transport on a timeout operation... would bringing that back be an option here? that feels more in line with scrapli things (who can say what that even means haha!) -- then you would have the option to catch the timeout and do whatever you need to do?

would love to hear any thoughts ya'll have!

**Comment by rlad78** [comment] 2023-04-30 17:08
I'm on the road this weekend so I can't be too thorough in my response. I believe what @erwinkinn and I are trying to accomplish isn't exactly within the typical use-case scope of `on_open` and `on_close`. 

For example, I currently pass a pair of functions that either increment a global counter on transport open, or decrement on transport close. This is so I can write to my debug logs to sanity check that my async lock are working properly and not allowing more concurrent SSH connections than my max limit. These functions are used in my connection "factory" regardless of driver class. Because of this, these functions need to check the passed `conn` for what driver class it's using and pull in the appropriate default on_open/close functions from the core/community drivers. These all need to be manually imported, as the default open/close functions are defined separately from the driver classes. 

(I'll try to edit this later with an example block to paint a clearer picture of what I mean)

From the documentation in what I believe is the "Advanced Usage" section, I got the impression that supplying a callable to the on_open/close driver arguments would _add_ the callable to the driver init/close instead of replacing the default functions. From what I've seen of the codebase, I can absolutely see why it would be difficult to change things around to check for a premature transport close. Would it be any easier to implement a custom callable for _before_ transport open and _after_ transport close? It might be out of the scope of this project, but if it isn't, let me know and I might be able to take a shot at getting that working.

**Comment by carlmontanari** [comment] 2023-05-10 00:01
hello again! just wanted to say -- "havent forgotten about this"! ill try to get some time to take a closer look this weekend! (and thanks a ton @rlad78 for the extra detail/example, much appreciated!)

**Comment by erwinkinn** [comment] 2023-05-10 04:18
Hello, Carl! Thank you for feeling the pulse ;)
I'm sorry for the delay with answering too (I was on two days vacation). 

Yes, my case is quite similar to what @rlad78 is talking about. But it's not a list -- an sqlalchemy controlled database though. Once the connection to my sever is opened I add a new `Connection` object which is actually defined by server's address, connection type (ssh, telnet) and user credentials. After this I try to manage this object state using those `on_open` and `on_close` callbacks. 
This leads me to a situation when I try to set the same `OPENED` state twice one by one because on_close was never called between.

I believe an output timeout is not the case to forcibly close the connection at all. For instance, I enter a long thinking command (e.g. tech support logs collection). It takes various amount of time for this command to complete (depends on how many logs are there). The connection is ok, it's just a command lie this. Why close it?

**Comment by carlmontanari** [comment] 2023-05-10 17:19
cool, appreciate the follow up @erwinkinn !!

> The connection is ok, it's just a command lie this. Why close it

this is not actually true in many cases and is basically the reason for the closing of the connection. scrapli *must* find the prompt in order to do... well basically anything hah, so if your command is still running and then you try to interact with the connection it will almost always be problematic in at least some way to scrapli (obviously could fail entirely causing another timeout or it could just have totally jacked up responses, etc.) -- so this is the historical reason for things I guess.

I think the simplest solution here that should work for both use cases here and also not be a ton of effort to implement is to add a flag to not close connections at timeout and simply just raise the connection. then you can do whatever you want to do. I *think* this could (should?!) just be a global flag... we've had [this](https://github.com/carlmontanari/scrapli/blob/main/scrapli/settings.py#L4) contraption for a while and it only does the one thing right now... but we could add a `NO_CLOSE_ON_TIMEOUT` option (or whatever better name) there so it could be set once globally and then the timeout decorator can just check it to see what it should do. I think defaulting to how things are today is what I would want to do.

do you both think that would work for what ya'll are tryin to do?

**Comment by erwinkinn** [comment] 2023-05-11 11:52
Yes, I understand the root cause of the problem is in that write and read operations are included into the single call (send_command or whatever). And yes it looks like for scrapli it's better to close the connection to prevent the related problems that are defined by scrapli architecture. 
But here we a talking not about whether we shoud (or should not) close the connection, but about when the connection is closed a callback registered as on_close callback must be called. So this _timeout_handler decorator has to have an access to this callback to call it.
The callback itself is an attribute of the driver. So does the channel. Hence channel knows nothing about this callback. May be we should register the callback deeper? May be place it in channel?

**Comment by rlad78** [comment] 2023-05-12 01:18
I feel like I can see the trouble that ensuring `on_close` _always_ be called on timeout would cause. Hypothetically, what would/should the expected behavior be if a user's `on_close` function references the previously existing (but now no longer functional) `conn` argument that gets passed to it? I imagine there's plenty of scripts out there that use `on_close` to do something like "write a message to the host's log" or "save configuration before leaving" etc. Forcing that to run even though there's potentially no connection could blow up a variety of different exceptions that these users' scripts are not accounting for. If the connection _is_ still open but Scrapli times out, I could see it very easily getting "lost" if it tried to execute more commands while not having a prompt ready.

I have to agree with @carlmontanari's idea of having an option set to not destroy the connection and raise it instead. That way we have more data to take action with as long as we properly catch it. In a perfect world, I'd love for there to be something like a connection-independent `after_close` and `before_open` callback, but that requires a lot of work for what seems to be a very niche issue.

**Comment by erwinkinn** [comment] 2023-05-12 04:58
Oh, yes, thank you. Precise potential trouble spotting. This is just yet another thing defined by the architecture. That's why it's better to have  the separate reader and writer objects like it's done for, say, asyncio. But never mind. 

How do you think, would it be a problem again once scrapli raises the connection as an exception parameter with no closing it?
Someone could hope the connection is closed and proceed with the another one opening more and more connections simultaneously ? 

To be honest, I already tend to agree with Carl -- "not broke wont fix". Because I have already have a crutch like:
```python
def _timeout_handler(func: Callable[..., Awaitable[Any]]):
    # See https://github.com/carlmontanari/scrapli/issues/285
    #
    @wraps(func)
    async def actor(self: DriverImpl, *args, **kwds):
        try:
            return await func(self, *args, **kwds)
        except ScrapliTimeout as exc:
            if not self.driver.channel.transport.isalive():
                await self._on_close(self.driver)
            raise exc

    return actor
```
Of course inside my `_on_close` there's a comment that the connection may be closed actually. 
And it's not worse than having one global flag. Because both of the solutions are based on my a priory knowledge about scrapli's standard behaviour. Once I've set such a kind of global flag I'm stll forced to have a try-cache block to handle the exception and to call my on_close callbacks manually. Hence flag gives me nothing but brings more extra complexity to the scrapli's code.

Sad to say this is not a first time I think that maybe scrapli is just not an option for me since it provides too few data exchange control (

@carlmontanari, I think we could close this issue. Sorry, for wasting a time.

**Comment by erwinkinn** [comment] 2023-05-12 12:56
Oh, @carlmontanari, before this issue is closed, please see the related PR. I did note this problem months ago but only now (due to the discussion) I actually came across this timeout issue. 
PR seems completely safe and has no backward compatibility issues.

**Comment by carlmontanari** [comment] 2023-05-13 17:30
hey again friends! going to close this out and follow up in #290!

thanks for all the great conversation and teamwork!! 🥳

**Closed by carlmontanari** 2023-05-13 17:30 UTC
Labels: bug
