### ISSUE TITLE
"Timed out sending input to device" if I add the "aaa group server tacacs+" config

### ISSUE THREAD

**Issue by artyomovs** [carlmontanari/scrapli#23] opened 2020-06-03 08:15 UTC
Hi all. The issue is: if I add this config by scrapli telnet, it fails with timeout issue. 
Here is the code:
```
import logging
from scrapli.driver.core import IOSXEDriver


logging.basicConfig(
    level=logging.DEBUG,
    format="%(name)s %(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[logging.FileHandler("scapli_debug.log"),logging.StreamHandler()]
)

logging.getLogger('transport').propagate = False

CONFIGS_1 = [
    'aaa group server tacacs+ Hello',
    'server name srv1',
]

cisco_s = {'host': 'X.X.X.X', 'auth_username': 'cisco', 'auth_password': 'cisco', 'auth_secondary':'cisco', 'transport': 'telnet', 'port': 23}
conn = IOSXEDriver(**cisco_s)
conn.open()
response = conn.send_configs(CONFIGS_1)
conn.close()
```

The fail traceback is:
`Traceback (most recent call last):
  File "scrapli_debug.py", line 28, in <module>
    response = conn.send_configs(CONFIGS_1)
  File "/usr/local/lib/python3.8/dist-packages/scrapli/driver/network_driver.py", line 688, in send_configs
    response = super().send_command(
  File "/usr/local/lib/python3.8/dist-packages/scrapli/driver/generic_driver.py", line 90, in send_command
    raw_response, processed_response = self.channel.send_input(
  File "/usr/local/lib/python3.8/dist-packages/scrapli/channel/channel.py", line 268, in send_input
    raw_result, processed_result = self._send_input(
  File "/usr/local/lib/python3.8/dist-packages/scrapli/decorators.py", line 77, in timeout_wrapper
    raise TimeoutError(message)
TimeoutError: Timed out sending input to device.`

**Screenshots**
![image](https://user-images.githubusercontent.com/4401664/83612505-28193800-a58b-11ea-8c72-6f6d20c6cf68.png)

**OS (please complete the following information):**
 - OS: Ubuntu 20
 - scrapli version: 2020.5.9

**Additional context**
Log 

> file:
[scrapli_debug.log](https://github.com/carlmontanari/scrapli/files/4721841/scrapli_debug.log)

**Comment by carlmontanari** [comment] 2020-06-03 13:33
Hi @artyomovs 

Thanks for submitting this issue!

I was able to reproduce your issue and it looks like this occurs because we currently do not allow for matching for the `+` character in config mode.

The fix for this is of course to just add that `+` character in the pattern match. You can check out this issue from @IDQDD [here](https://github.com/carlmontanari/scrapli/issues/24) -- they have a similar issue and have patched it temporarily by passing in modified privilege levels to scrapli.

I think the privilege pattern will ultimately get updated to look like this below:

```
    "configuration": (
        PrivilegeLevel(
            pattern=r"^[a-z0-9.\-_@/:]{1,63}\(conf[a-z0-9.\-@/:\+]{0,32}\)#$",
            name="configuration",
            previous_priv="privilege_exec",
            deescalate="end",
            escalate="configure terminal",
            escalate_auth=False,
            escalate_prompt="",
        )
    ),
```

This pattern will fix this issue as well as @IDQDD's issue.

To make sure we dont run into this again I'm going to add a few tests to ensure that we are matching all the types of base prompts -- i.e. "normal" exec/privilege-exec/config as well as more special prompt pattens like this tacacs+ mode or ssh key config mode.

This should be in develop by this weekend, I'll update this issue when I get it pushed up. I'm also planning/hoping on making a release to pypi this weekend, so hopefully this will make it up there this weekend as well!

Thanks again for submitting this! 

Carl

**Comment by carlmontanari** [comment] 2020-06-06 21:12
Hi again @artyomovs

The fix for this has now been pushed to master and released. I'll go ahead and close this now, but feel free to reopen if for some reason the fix does not work.

Thanks again for reporting this!

Carl

**Closed by carlmontanari** 2020-06-06 21:12 UTC
Labels: bug

**Comment by artyomovs** [comment] 2020-06-11 14:18
> Hi again @artyomovs
> 
> The fix for this has now been pushed to master and released. I'll go ahead and close this now, but feel free to reopen if for some reason the fix does not work.
> 
> Thanks again for reporting this!
> 
> Carl

Thank you very much:)
