### ISSUE TITLE
Connection closed due to expired password, without Scrapli (asyncssh) realizing it or observing timeout values

### ISSUE THREAD

**Issue by hdmoreland** [carlmontanari/scrapli#272] opened 2022-12-14 17:11 UTC
**Describe the bug**
I have a Cisco node (using the genericdriver for various reasons -- work in telco space) that has an expired password and as a result immediately disconnects upon successful login. Despite this, Scrapli does not recognize that the connection is closed and instead attempts to run the command. Scrapli also does not observe the timeout value, hanging indefinitely. 

**To Reproduce**

Code:

1. My Script:
```
async def execute_ssh(self):

    get_ssh_config = {'host': 'ip', 'port': 22, 'auth_username': 'username', 'auth_password': 'pass', 'auth_strict_key': False, 'transport': 'asyncssh', 'comms_prompt_pattern': 'local].+#', 'timeout_socket': 10.0, 'timeout_transport': 10.0, 'timeout_ops': 10.0}

    command = 'show system uptime'

    try:
        async with AsyncGenericDriver(**get_ssh_config) as conn:
            print('connected') # This does print successfully
                try:
                    result = await conn.send_command(command)
                    print('result recieved') # This never prints
                except Exception as e:
                    print('error sending command') # This never prints
    except Exception as e:
        print('error connecting') # This never prints
    
return self # This is never executed
```

2. What you're connecting to (vendor, platform, version): Cisco VPC-SI (Cisco ASR 5500 chassis running StarOS)
3. Anything else relevant: My timeout params work great. For nodes with valid passwords, if I run sleep 15 with my timeout at 10 they will consistently timeout. For nodes that are offline, they also timeout as expected.

**Expected behavior**
I expected one of the timeout values to be reached (I have specified all 3) and for the command execution to exit with an exception.

**Stack Trace**
No issues detected, Scrapli hangs indefinitely attempting to run the command despite the timeout values.

**Screenshots**
Example output when attempting to SSH from CLI:
```
[whoami]$ ssh username@hostname

       ++++++++++++++++ !!! WARNING !!! +++++++++++++++
       +                                              +
       +    ! This is a restricted access system !    +
       + All activity on it is subject to monitoring! +
       +  Unauthorised access is prohibited and will  +
       +                 be prosecuted!               +
       + By continuing past this point you expressly  +
       +             agree to these terms!            +
       +                                              +
       ++++++++++++++++ Have a nice day! ++++++++++++++
          username@hostname's password:
Last login: Wed Dec 14 16:35:36 +0000 2022 on pts/1 from internal_ip.

        **********************************************
        *                                            *
        *          Company Name Cisco VPC-SI           *
        *                  hostname             *
        *                                            *
        **********************************************

Failure: Password Expired (even beyond grace period, if configured). Contact Security Administrator to reset password
Failure: Password change required
Connection to hostname closed.
```

**OS (please complete the following information):**
 - OS: Centos + Docker Container running Python 3.11
 - scrapli version: 2022.7.30.post1

**Additional context**
I have noticed I get an expected error using Paramiko:
`OSError('Socket is closed',)`

**Comment by carlmontanari** [comment] 2022-12-14 17:56
👋 hey there. In *theory* this shouldn't be happening because...

*If* the connection does indeed get closed by the remote server then when you do `conn.send_command(blah)` we *should* raise an exception complaining about trying to run a command on a connection that isn't open. 

*If* the connection is still open (in the case of asyncssh meaning we still have stdin/stdout/session objects alive/functional in the asyncssh transport) normal timeouts should work.

*If* some underlying transport object has been closed and is no longer available, I'd expect us to see some kind of attribute/error or other error coming from asyncssh or whatever transport.

Could you drop a `conn.isalive()` and a `conn.transport.isalive()` in there after your "connected" print line there to see whats up. You mentioned paramiko as well -- is this repeatable on sync transports as well? Is this something I can make some general csr/3560 switch do easily enough (as in make my switch complain that a users password is expired like this)? I don't think there will be anything interesting in logs, but could you also snag the scrapli logs and maybe also channel logs to see if there is anything obvious in there.

**Comment by hdmoreland** [comment] 2022-12-14 19:05
Hey! Thanks for the quick response. I really appreciate it. 

I have added conn.isalive() and conn.transport.isalive() to my code as follows, including a sleep(1). Each time it prints True, so the objects appear alive.
```
async def execute_ssh(self):

    get_ssh_config = {'host': 'ip', 'port': 22, 'auth_username': 'username', 'auth_password': 'pass', 'auth_strict_key': False, 'transport': 'asyncssh', 'comms_prompt_pattern': 'local].+#', 'timeout_socket': 10.0, 'timeout_transport': 10.0, 'timeout_ops': 10.0}

    command = 'show system uptime'

    try:
        async with AsyncGenericDriver(**get_ssh_config) as conn:

            print('connected') # This does print successfully

            print(f'conn.isalive: {conn.isalive()}') # Prints True
            print(f'conn.transport.isalive: {conn.transport.isalive()}') # Prints True

            sleep(1) # Just wanted to ensure it remained alive

            print(f'conn.isalive: {conn.isalive()}') # Prints True
            print(f'conn.transport.isalive: {conn.transport.isalive()}') # Prints True

                try:
                    result = await conn.send_command(command)
                    print('result recieved') # This never prints
                except Exception as e:
                    print('error sending command') # This never prints
    except Exception as e:
        print('error connecting') # This never prints
    
return self # This is never executed
```
 
When I run using system transport I expectedly get the following error. I can try other sync transport options to confirm it's repeatable if needed.
```
encountered EOF reading from transport; typically means the device closed the connection
```

I do not have experience with the 3560 specifically, but the account was created on this device using the following syntax. If you can configure accounts with an expiry date on the switch, you should (hopefully) be able to replicate.
```
config-administrator username encrypted password *** expiry-date 2022:10:31:19:18:27
```
Here are the Scrapli logs:
```
3     | 2022-12-14 13:01:09,569 | INFO     | 10.241.215.47:22          | opening connection to 'ip' on port '22'
4     | 2022-12-14 13:01:09,569 | DEBUG    | 10.241.215.47:22          | opening transport connection to 'ip' on port '22'
5     | 2022-12-14 13:01:10,686 | DEBUG    | 10.241.215.47:22          | transport connection to 'ip' on port '22' opened successfully
6     | 2022-12-14 13:01:10,686 | INFO     | 10.241.215.47:22          | connection to 'ip' on port '22' opened successfully
7     | 2022-12-14 13:01:11,689 | INFO     | 10.241.215.47:22          | sending channel input: show system uptime; strip_prompt: True; eager: False
8     | 2022-12-14 13:01:11,689 | DEBUG    | 10.241.215.47:22          | write: 'show system uptime'
```

I will look into how to get the channel logs now. If you would like, I can try to ssh into the machine with asyncssh on it's own, without Scrapli. Hopefully (for my sake, not yours) the issue is not on that end, I think there is less support there.

**Comment by carlmontanari** [comment] 2022-12-14 19:36
Cool, thank for the extra info! I'm glad system transport works as expected, that is at least a bit of good news! I think probably this is up to my implementation of the asyncssh transport (if I had to guess). Trying w/ just asyncssh would be great if you can check that out.

I'm wondering if we need to do something like `self.stdin.is_closing()` somewhere around [here](https://github.com/carlmontanari/scrapli/blob/main/scrapli/transport/plugins/asyncssh/transport.py#L276) or even on this same line. My current check is kind of basic: "hey is stdin not None", but that may have been the wrong approach, we may want to be checking this closing bits. But... `isalive` does check this already so maybe that won't do the trick... 🤔 its been a long time since ive looked deeply at asyncssh things, we may need to poke about there more to resolve this. If you're up for it that would be really great since I'm not really doing much (any) networking things nowadays, but I'm more than happy to review/merge any fixes we can find here!

**Comment by hdmoreland** [comment] 2022-12-14 19:59
Understood, thanks for that information. I can take a peak around there and see what I can find. 

Interestingly enough, when I run the command using the following simple asyncssh code it actually completed. It still will not complete with system transport. I still cannot SSH into the node at that IP using that login info using any of the SSH clients I have on my machine. I suspect it might be something related to the terminal type or settings? I am going to see if I can get the error to reproduce in asyncssh by changing the terminal settings.

```
import asyncio, asyncssh, sys

async def run_client() -> None:
    async with asyncssh.connect('ip', username=username, password=password, known_hosts=None) as conn:
        result = await conn.run('show system uptime', check=True)
        print(result.stdout, end='')

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```

**Comment by carlmontanari** [comment] 2022-12-14 20:20
> when I run the command using the following simple asyncssh code it actually completed

By that you mean it times out or raises an exception like it couldn’t complete the command? 

To summarize the main problem I think: why do we not hit a timeout — we should because send_command is wrapped with the timeout decorator. I assume(total assumption, am on mobile on holiday so not able to really dig in) this is because the *write* (or something at least…) is blocking somehow. I think just dropping some prints/breakpoints in/around send_input in the async channel should help track this down.

> still will not complete with system transport


As in hit eof? I think that would be the expected behavior here ya? Maybe I misread something here though!

**Comment by hdmoreland** [comment] 2022-12-14 20:26
> By that you mean it times out or raises an exception like it couldn’t complete the command?

Believe it or not, no. I mean it actually prints out the correct result of 'show system uptime'. I tested with 'show version' as well. It successfully logged in using the same IP, port, username, password. Here is the output of that asyncssh code:

```
System uptime: 135D 1H 35M

Active Software:
  Image Version:                  info
  Image Build Number:             info
  Image Description:              info
  Image Date:                     info
  Boot Image:                     info
```

> As in hit eof? I think that would be the expected behavior here ya? Maybe I misread something here though!

Correct, sync system transport still hits eof! I 100% agree that is expected behavior, I was just confirming that I still see the issue using sync system transport and using my own ssh clients despite asyncssh working normally (without error, printing actual response from node).

**Comment by carlmontanari** [comment] 2022-12-14 20:39
> Believe it or not, no. I mean it actually prints out the correct result of 'show system uptime'. I tested with 'show version' as well. It successfully logged in using the same IP, port, username, password. Here is the output of that asyncssh code:

ahhh ok I think I see where you were going with terminal type then -- I could see some scenario where this is ignored if vt100 vs xterm or something. interesting!

> Correct, sync system transport still hits eof

Ok dope, just wanted to make sure I wasn't goin crazy :)

**Comment by hdmoreland** [comment] 2022-12-14 22:40
Looks like "self._read_until_prompt()" in scrapli/channel/async_channel.py is blocking. Specifically the while true loop:

```
        while True:
            b = await self.read()

            read_buf.write(b)

            search_buf = self._process_read_buf(read_buf=read_buf)

            channel_match = re.search(
                pattern=search_pattern,
                string=search_buf,
            )

            if channel_match: # This is never true
                return read_buf.getvalue()
```

I added a @timeout_wrapper to the _read_until_prompt() function on line 112, but that did not change anything. Going to keep looking at it, but just wanted to document my findings so far and see if you had suggestions now that the blocking function is narrowed down.

**Comment by carlmontanari** [comment] 2022-12-15 18:54
> it sounds like that is the functionality I am needing 

in theory "yes", but also "no", I think what is happening is something along the lines of "connection gets closed but not "all the way/correctly", so we dont read eof, and there is nothing there for us to read so we just block trying to read something that doesn't exist".

inspecting the asyncssh session in the transport to see if it thinks it is still open, or if it has any indication that it is not open so we can act on that accordingly is probably what we need. the rest of scrapli things should "just work" ™️ 🤣

**Comment by carlmontanari** [comment] 2023-01-12 16:34
hey @hdmoreland just wanted to bump this up to see if ya had found anything else out?

**Comment by carlmontanari** [comment] 2023-01-24 15:43
hey there, going to close this for now to appease my ocd, but defo feel free to reopen if there's some more to do here!

thanks a bunch!

**Closed by carlmontanari** 2023-01-24 15:43 UTC
Labels: bug
