### ISSUE TITLE
Timed out connecting to host - Connection to device with authentication via Tacacs

### ISSUE THREAD

**Issue by timofmax** [carlmontanari/scrapli#167] opened 2021-08-21 14:17 UTC
**Describe the bug**
Two similar setup of switches:
1) Authentication local - scrapli works ✅
2)  Authentication via tacacs creds - scrapli fails 

**To Reproduce**
1.

```
from scrapli import Scrapli
import logging
from datetime import datetime

logging.basicConfig(
    format = '%(threadName)s %(name)s %(levelname)s: %(message)s',
    level=logging.INFO)

r1 = {
   "host": "10.1.1.1",
   "auth_username": "admin",
   "auth_password": "123456",
   "auth_secondary": "123456",
   "auth_strict_key": False,
   "platform": "cisco_iosxe",
    "timeout_socket": 5,
    "timeout_transport": 10
}

#no enable password required to login via tacacs
r2 = {
   "host": "10.1.1.2",
   "auth_username": "user_at_tacacs",
   "auth_password": "123456",
   "auth_strict_key": False,
   "platform": "cisco_iosxe",
    "timeout_socket": 5,
    "timeout_transport": 10
}

def get_session():
    with Scrapli(**r2) as ssh:
        logging.info(datetime.now())
        print(ssh.get_prompt())

if __name__ == "__main__":
    get_session()

```
2. What you're connecting to (vendor, platform, version)
_Cisco, Catalyst 9300, 17.3.3_
3. Anything else relevant
Replacing r1 and r2 in script manually - expecting r2 to execute succesfully as r1 does.

**Expected behavior**
Replacing r1 and r2 in script manually - expecting r2 to execute succesfully as r1 does.

**Stack Trace**
Copy of your stack trace here, please format it properly using triple back ticks (top left key on US keyboards!)
```
MainThread scrapli INFO: Driver '<class 'scrapli.driver.core.cisco_iosxe.sync_driver.IOSXEDriver'>' selected from scrapli core drivers
MainThread scrapli.driver INFO: opening connection to '10.1.1.2' on port '22'
ThreadPoolExecutor-0_0 scrapli.channel CRITICAL: Timed out connecting to host
Traceback (most recent call last):
  File "/Users/lucky/untitled/scrapli_test.py", line 40, in <module>
    get_session()
  File "/Users/lucky/untitled/scrapli_test.py", line 34, in get_session
    with Scrapli(**r2) as ssh:
  File "/Users/lucky/untitled/venv/lib/python3.8/site-packages/scrapli/driver/base/sync_driver.py", line 40, in __enter__
    self.open()
  File "/Users/lucky/untitled/venv/lib/python3.8/site-packages/scrapli/driver/base/sync_driver.py", line 86, in open
    self.channel.channel_authenticate_ssh(
  File "/Users/lucky/untitled/venv/lib/python3.8/site-packages/scrapli/decorators.py", line 276, in decorate
    return self._multiprocessing_timeout(
  File "/Users/lucky/untitled/venv/lib/python3.8/site-packages/scrapli/decorators.py", line 337, in _multiprocessing_timeout
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/lucky/untitled/venv/lib/python3.8/site-packages/scrapli/channel/sync_channel.py", line 291, in channel_authenticate_ssh
    self._ssh_message_handler(output=authenticate_buf)
  File "/Users/lucky/untitled/venv/lib/python3.8/site-packages/scrapli/channel/base_channel.py", line 280, in _ssh_message_handler
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: Timed out connecting to host

```
**Screenshots**
If applicable, add screenshots to help explain your problem, but do note that formatted text is much preferred over
 screenshots!

**OS (please complete the following information):**
 - OS: [e.g. Ubuntu, MacOS, etc. - Note scrapli is *not* thoroughly tested on Windows and some/many things will not
  be supported]
macOS Catalina
 - scrapli version
2021.7.30

**Additional context**

**Comment by carlmontanari** [comment] 2021-08-21 15:41
Hey @timofmax thanks for raising this!

Could you show what the auth/login process looks like for the host with tacacs please? That and if you could snag logs (example [here](https://github.com/carlmontanari/scrapli/blob/master/examples/logging/opinionated_logging.py)) that would be great. We basically do pattern based searching for user/pass inputs when using `system` transport so most likely culprit here is that the pattern is not matching whatever the tacacs prompts are. 

You can also give this a shot w/ ssh2 or paramiko transports -- since those work "out of channel".

Thanks!

Carl

**Comment by timofmax** [comment] 2021-08-22 14:07
Hey Carl, appreciate your swift response.
here is auth/login process 
```
lucky@M-M8KB:~$ ssh admin@10.1.1.2
password:
Authentication succeeded. Your password will expire in 10 weeks + 1 days  + 18 hours  + 16 Minutes

sw.with.tacacs.auth#
sw.with.tacacs.auth#
```

here is logs
```
ID    | TIMESTAMP               | LEVEL    | (UID:)HOST:PORT           | MESSAGE
1     | 2021-08-22 15:56:53,823 | DEBUG    |                           | Scrapli factory initialized
2     | 2021-08-22 15:56:53,823 | INFO     |                           | Driver '<class 'scrapli.driver.core.cisco_iosxe.sync_driver.IOSXEDriver'>' selected from scrapli core drivers
3     | 2021-08-22 15:56:53,824 | DEBUG    | 10.1.1.2:22              | load core transport requested
4     | 2021-08-22 15:56:53,827 | DEBUG    | 10.1.1.2:22              | core transport 'system' loaded successfully
5     | 2021-08-22 15:56:53,827 | DEBUG    | 10.1.1.2:22              | created transport 'open_cmd': '['ssh', '10.1.1.2', '-p', '22', '-o', 'ConnectTimeout=5', '-o', 'ServerAliveInterval=10', '-l', 'admin', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-F', '/dev/null']'
6     | 2021-08-22 15:56:53,827 | DEBUG    | 10.1.1.2:22              | generating combined network comms prompt pattern
7     | 2021-08-22 15:56:53,827 | DEBUG    | 10.1.1.2:22              | setting 'comms_prompt_pattern' value to '(^[\w.\-@/:]{1,63}>$)|(^[\w.\-@/:]{1,63}#$)|(^[\w.\-@/:]{1,63}\([\w.\-@/:+]{0,32}\)#$)|(^([\w.\-@/+>:]+\(tcl\)[>#]|\+>)$)'
8     | 2021-08-22 15:56:53,827 | INFO     | 10.1.1.2:22              | opening connection to '10.1.1.2' on port '22'
9     | 2021-08-22 15:56:53,827 | DEBUG    | 10.1.1.2:22              | opening transport connection to '10.1.1.2' on port '22'
10    | 2021-08-22 15:56:53,856 | DEBUG    | 10.1.1.2:22              | transport connection to '10.1.1.2' on port '22' opened successfully
11    | 2021-08-22 15:56:53,856 | DEBUG    | 10.1.1.2:22              | attempting in channel ssh authentication
12    | 2021-08-22 15:56:54,038 | DEBUG    | 10.1.1.2:22              | read : b"Warning: Permanently added '10.1.1.2' (RSA) to the list of known hosts.\npassword: "
13    | 2021-08-22 15:56:56,368 | DEBUG    | 10.1.1.2:22              | write: REDACTED
14    | 2021-08-22 15:56:56,369 | DEBUG    | 10.1.1.2:22              | write: '\n'
15    | 2021-08-22 15:56:56,369 | DEBUG    | 10.1.1.2:22              | read : b'\nAuthentication succeeded. Your password will expire in 10 weeks + 1 days  + 18 hours  + 8 Minutes \n'
16    | 2021-08-22 15:56:56,415 | DEBUG    | 10.1.1.2:22              | write: REDACTED
17    | 2021-08-22 15:56:56,415 | DEBUG    | 10.1.1.2:22              | write: '\n'
18    | 2021-08-22 15:56:56,415 | DEBUG    | 10.1.1.2:22              | read : b'123456\n\nsw.with.tacacs.auth#'
19    | 2021-08-22 15:56:56,504 | DEBUG    | 10.1.1.2:22              | write: '\n'
20    | 2021-08-22 15:56:56,505 | DEBUG    | 10.1.1.2:22              | read : b'123456\n'
21    | 2021-08-22 15:57:06,515 | CRITICAL | 10.1.1.2:22              | transport operation timed out, closing transport
22    | 2021-08-22 15:57:06,516 | DEBUG    | 10.1.1.2:22              | closing transport connection to '10.1.1.2' on port '22'
23    | 2021-08-22 15:57:06,621 | CRITICAL | 10.1.1.2:22              | encountered EOF reading from transport; typically means the device closed the connection
24    | 2021-08-22 15:57:06,724 | DEBUG    | 10.1.1.2:22              | transport connection to '10.1.1.2' on port '22' closed successfully

```

**Comment by carlmontanari** [comment] 2021-08-22 15:43
Perfect, thank you @timofmax ! 

Looks like this is being caused by some lazy password pattern checking I built into the "in channel" ssh auth. Basically we check for "password" in the bytes we read from the server... if we see that we assume we are at a password prompt and send the password and a return (hence the `REDACTED` showing up more than it should be in there).

I was actually thinking I should fix this the other day since I did a slightly better job implementing it on the go side over in scrapligo. Let me try to get a branch pushed up that you can try out. Also if you are in a pinch -- this should *not* be an issue with the other transports, so that could be a workaround in the meantime if ya need it!

Will crank out that branch and update shortly!

Carl

**Comment by timofmax** [comment] 2021-08-22 16:05
> paramiko

Dear @carlmontanari thank you for advice
with parameters ssh2 or paramiko works perfectly.

**Comment by carlmontanari** [comment] 2021-08-22 16:38
Hey @timofmax 

If you don't mind -- could you try to install the `in-channel-ssh-improvements` branch... I made some improvements that I think should fix this issue. You can install it like: `pip install git+https://github.com/carlmontanari/scrapli.git@ in-channel-ssh-improvements#egg=scrapli`.

I'll open a pr for that and if it works for ya get it moved over to develop branch!

Carl

**Comment by carlmontanari** [comment] 2021-09-01 12:47
Gunna close this and merge #168 -- but feel free to reopen if there are still issues!

Carl

**Closed by carlmontanari** 2021-09-01 12:47 UTC
Labels: bug
