### ISSUE TITLE
TimeoutError('Timed out reading from transport') for Junos

### ISSUE THREAD

**Issue by ilyapetrashkevich** [carlmontanari/scrapli#36] opened 2020-07-16 20:09 UTC
Scrapli works well for cases when configuration is error free, but if there is a typo - it will hang for a while untill Timeout is reached, but the session would be still connected

Here is a basic configuration that I used:

from scrapli.driver.core import JunosDriver
my_device = {
    "host": "192.168.226.139",
    "auth_username": "test",
    "auth_password": "~!QAZXSW@",
    "auth_strict_key": False
}
conn = JunosDriver(**my_device)
conn.open()
print(conn.send_command("configure exclusive").result)
commands = ["set system services ssh","set system services nestconf ssh"]
for command in commands:
    print("sending line - "+command)
    response = conn.send_config(command, strip_prompt=False)
    print(response.result)
conn.close()

**To Reproduce**
1. run the script with several commands and one of them should contain typo
2. Junos vMX with VCP/VFP v 17.2R1.13

**Expected behavior**
I would expect to have it like "set system services nestconfssh" as Junos parser would not recognize command and get an error from parser, but I don't see that command was ever entered (by using - "show log interactive-commands" on vMX)

**Stack Trace**
```
/home/python/PycharmProjects/config_deploy/venv/bin/python /home/python/PycharmProjects/config_deploy/scrapli_test.py
warning: uncommitted changes will be discarded on exit
Entering configuration mode

[edit]
sending line - set system services ssh
[edit]
test@LAB-ROUTER#
sending line - set system services nestconf ssh
Traceback (most recent call last):
  File "/home/python/PycharmProjects/config_deploy/scrapli_test.py", line 16, in <module>
    response = conn.send_config(command, strip_prompt=False)
  File "/home/python/PycharmProjects/config_deploy/venv/lib/python3.8/site-packages/scrapli/driver/network_driver.py", line 392, in send_config
    multi_response = self.send_configs(
  File "/home/python/PycharmProjects/config_deploy/venv/lib/python3.8/site-packages/scrapli/driver/network_driver.py", line 445, in send_configs
    response = super().send_command(
  File "/home/python/PycharmProjects/config_deploy/venv/lib/python3.8/site-packages/scrapli/driver/generic_driver.py", line 75, in send_command
    raw_response, processed_response = self.channel.send_input(
  File "/home/python/PycharmProjects/config_deploy/venv/lib/python3.8/site-packages/scrapli/channel/channel.py", line 165, in send_input
    raw_result, processed_result = self._send_input(
  File "/home/python/PycharmProjects/config_deploy/venv/lib/python3.8/site-packages/scrapli/decorators.py", line 77, in timeout_wrapper
    return future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/python/PycharmProjects/config_deploy/venv/lib/python3.8/site-packages/scrapli/channel/channel.py", line 192, in _send_input
    self._read_until_input(channel_input=bytes_channel_input)
  File "/home/python/PycharmProjects/config_deploy/venv/lib/python3.8/site-packages/scrapli/channel/channel.py", line 82, in _read_until_input
    output += self._read_chunk()
  File "/home/python/PycharmProjects/config_deploy/venv/lib/python3.8/site-packages/scrapli/channel/channel.py", line 47, in _read_chunk
    new_output = self.transport.read()
  File "/home/python/PycharmProjects/config_deploy/venv/lib/python3.8/site-packages/scrapli/decorators.py", line 104, in requires_open_session_wrapper
    return wrapped_func(*args, **kwargs)
  File "/home/python/PycharmProjects/config_deploy/venv/lib/python3.8/site-packages/scrapli/decorators.py", line 76, in timeout_wrapper
    raise TimeoutError(message)
TimeoutError: Timed out reading from transport


```

**OS:**
 - OS: Ubuntu 20.04
 - scrapli version 2020.7.12

**Comment by carlmontanari** [comment] 2020-07-17 00:45
Hi @ilyapetrashkevich 

Thanks for raising this! I can reproduce this with my vsrx. I'm a little on the fence about what to do about this. What is happening is that scrapli sends the command as expected, however we get an output like this from the junos box:

```
DEBUG:scrapli.channel-172.18.0.15:Read: b'\n                              ^\nsyntax error.\nvrnetlab# set system services nestconf   \x08\x08\x08ssh'
```

Because of the output we receive the input is never read, and this causes the timeout.

This reading of the channel inputs has been a core part of scrapli from the beginning -- we never send a return/enter until after the input has been read off the channel. This input is also "consumed' by scrapli so the inputs never show up in the `response.result`/have to be stripped out of the result. I have considered adding an option to bypass all of the input verification/reading, however the implications of doing so would mean that results would end up having the inputs in them/or need the inputs stripped from them.

All of that said... fixing this would be fairly easy in one of a few ways:

1. adding a "input_verify" flag and allowing users to set it to false -- thus bypassing all of the input "checking" (and probably making scrapli faster to boot), however this would mean doing some "cleaning" in the response object to make the outputs look like they do currently to keep things consistent.
2. adding a "lazy_verify" flag (or something like that) that allows for checking that all the words of an input are read, but doesn't care about the order, something like this:

```
        while True:
            output += self._read_chunk()
            if not auto_expand and channel_input in output:
                break
            if auto_expand and self._process_auto_expand(
                output=output, channel_input=channel_input
            ):
                break
            if lazy_input_verification:
                split_output = output.split()
                if all(input_word in split_output for input_word in channel_input.split()):
                    break

```

^ this is in the channel `_read_until_input` method. 

3. checking if there is a backspace in the output `\x08` -- if there is we can assume something is up (either terminal width didn't get set nicely, or we have an invalid input issue like this) and we can either return there or do some parsing/checking to see if all the input made it in.
4. we can say that this is a "bad" design by juniper (I personally think it is, not that that matters too much :)) and expect users to simply handle this on their own w/ some kind of exception handling and/or we assume that users are only sending valid commands -- probably not the nicest answer for users, however clearly the simplest for scrapli, and perhaps the "most right" answer in terms of sticking to the philosophy of how scrapli deals with things.

Somewhat related FYI -- I tested sending this command manually and seeing if it shows up in the "show log interactive-commands" log output, and it does *not* -- so I think juniper just ignores "bad" commands anyway. Doesn't really matter for scrapli/this issue just thought id share that!

So at this point I'm not really sure how I want to approach handling this, I'd be curious to get your feedback based on the above. I'll probably revisit this this weekend, so I'll sleep on it between now and then and wait for your reply!

Thanks again for opening this!

Carl

**Comment by ilyapetrashkevich** [comment] 2020-07-17 06:19
Hello, Carl.
Well, from my point of view there should not be any additional steps if it's not compliant with philosophy :) I like scrapli that it's extremely fast and I don't need to wait as in other "timer-based-modules" :)
I would just wonder if scrapli may return this output in "response" variable, so me/other user could make an exception checking. So smth like for cisco ios when I get output containing "%" (here goes piece of my "prod" code):
```
result = net_connect.send_config(command, strip_prompt=False)
print(result.result)
# here parsing output to find if symbol "%" exists in returned output
# if there is no match .find will show "-1", otherwise - location(0 or another)
if result.result.find("%") >= 0:
  show_print_message("We are at failed command, please verify syntax/examine error")
  return ("There was a failure with one of the commands, please verify syntax: \n" + command_prompt + command + "\n" + result.result)
  exit(-1)
```

Your fix would be really appreciated!

**Comment by carlmontanari** [comment] 2020-07-17 14:08
In your example above scrapli will already mark the response object as failed! This is handled [here](https://github.com/carlmontanari/scrapli/blob/master/scrapli/response.py#L125) in the response object, and the `failed_when_contains` list is auto populated in the [driver](https://github.com/carlmontanari/scrapli/blob/master/scrapli/driver/core/cisco_iosxe/driver.py#L99) (or you can pass this as an argument at the driver level or at a command/config level).

Quick example:

```
>>> from scrapli.driver.core import IOSXEDriver
>>> device = {"host": "172.31.254.1", "auth_username": "vrnetlab", "auth_password": "VR-netlab9", "auth_strict_key": False}
>>> conn = IOSXEDriver(**device)
>>> conn.open()
>>> cmd_response = conn.send_command("bad command")
>>> cmd_response.result
"         ^\n% Invalid input detected at '^' marker."
>>> cmd_response.failed
True
>>> cfg_response = conn.send_config("bad config")
>>> cfg_response.result
"                  ^\n% Invalid input detected at '^' marker."
>>> cfg_response.failed
True
>>> 
```

I know that doesn't address the real issue here, but maybe that will save you some time/effort for IOSXE stuff! :) 


The problem for the juniper box (and it is only a problem for *juniper*) is that it "interrupts" the command you input w/ the error message. This is a behavior that IMO "breaks" the "encoding" of the cli -- in other words for a cli I would expect to be able to enter a command, have some response and ultimately expect to be back at some prompt. By interrupting the command input, juniper is breaking this "encoding" pattern (obviously there is no formal/official encoding for cli things, but this is my general view of how the cli should operate). If juniper did not "interrupt" the output, normal scrapli error checking would work just as in the IOSXE example above.

If this were happening on a non-core platform I would have closed this ticket and asked you to work around it. However given that this is a core platform and is of course a big and important vendor I think I will try to find a fix for this that does not break any scrapli functionality for core (or scrapli-netconf), and then hopefully we won't run into vendors doing stupid things on the cli in the future :D 

I will try to find a fix that I am happy with this weekend and will keep you posted -- hopefully you can work around this in the mean time.

Thanks for your input/help with this!

Carl

**Comment by ilyapetrashkevich** [comment] 2020-07-17 16:42
Hello, Marc.
Yeah, I meant that I would like to have same aproach for Junos as for IOSXE :)
Luckily I'm using core driver :D 
Okay, as of now I will tell my team-members that they should verify configuration before providing it to scrapli, but you never know for sure...

**Comment by ilyapetrashkevich** [comment] 2020-07-17 16:45
Also additional bug I faced just now - when command looks like:
```
cmd_response = conn.send_command("set poli poli test from commun test")
```
I get same error, but in the interactive log file it shows:
```
UI_CMDLINE_READ_LINE: User 'test', command 'set testfromcommunitytestpoli'
```

However I have to mention that this is purely valid command if to enter it directly in the cli. Do you want me to create another issue related to it?

Thanks!

**Comment by carlmontanari** [comment] 2020-07-17 16:54
Since we disable complete on space w/ junos you'll have to send the "full" commands -- not the abbreviations. `set policy-options policy-statement test from community test` should work.

```
vrnetlab> set cli complete-on-space off 
Disabling complete-on-space

vrnetlab> configure private 
warning: uncommitted changes will be discarded on exit
Entering configuration mode

[edit]
vrnetlab# set poli poli
              ^
syntax error.
vrnetlab# set poli poli   
error: syntax error: poli

[edit]
vrnetlab# set policy-options policy-statement test from community test" 

[edit]
vrnetlab# ```

^ you can see w/ the abbreviated commands that junos does the "interrupting" thing and thus causes the same issue.

I'll keep ya posted on if/how I decide to "fix" this!

**Comment by ilyapetrashkevich** [comment] 2020-07-17 17:00
> set cli complete-on-space off

aha, and what was the reason behind it? just curious

**Comment by carlmontanari** [comment] 2020-07-17 17:06
Pretty much for all the reasons we see here -- with `complete-on-space` set to "on" what we enter in the channel is not what is ultimately reflected in the channel output, and that is a bad thing because it breaks this "encoding" pattern I was talking about.

Ideally juniper would "honor" this complete-on-space setting in config mode because if they did we wouldn't be having the issue with the invalid command input breaking things.

**Comment by carlmontanari** [comment] 2020-07-18 22:47
Hello again @ilyapetrashkevich -- I think I've got a workaround for this I am relatively happy with. Could you give this script a try with the develop branch and let me know if it fixes things for you?

You can install the develop branch like so:

```
pip install -e git+https://github.com/carlmontanari/scrapli.git@develop#egg=scrapli
```

Thanks for working with me on this!

Carl

**Comment by ilyapetrashkevich** [comment] 2020-07-19 09:27
Hello, Carl.
Yes, looks perfect. However added another command and it's producing same timeout:
```
from scrapli.driver.core import JunosDriver

my_device = {
    "host": "192.168.226.139",
    "auth_username": "test",
    "auth_password": "~!QAZXSW@",
    "auth_strict_key": False
}

conn = JunosDriver(**my_device)
conn.open()
print(conn.send_command("configure exclusive").result)
commands = ["set system services ssh","set system services nestconf ssh", "set system servers ssh", "set system hosts-name sdf", "set system syslog hosts 1.1.1.1 log-prefix LAB-ROUTER"]
for command in commands:
    print("sending line - "+command)
    response = conn.send_config(command, strip_prompt=False)
    print(response.result)
conn.close()
```

Traceback:
```
python@ubuntu:~/PycharmProjects/config_deploy$ python3 scrapli_test.py 
warning: uncommitted changes will be discarded on exit
Entering configuration mode

[edit]
sending line - set system services ssh
[edit]
test@LAB-ROUTER#
sending line - set system services nestconf ssh
                                     ^
syntax error.

[edit]
test@LAB-ROUTER#
sending line - set system servers ssh
                            ^
syntax error.

[edit]
test@LAB-ROUTER#
sending line - set system hosts-name sdf
                            ^
syntax error.

[edit]
test@LAB-ROUTER#
sending line - set system syslog hosts 1.1.1.1 log-prefix LAB-ROUTER
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/scrapli-2020.7.12-py3.8.egg/scrapli/decorators.py", line 72, in timeout_wrapper
    result = future.get(timeout=timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 764, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scrapli_test.py", line 16, in <module>
    response = conn.send_config(command, strip_prompt=False)
  File "/usr/local/lib/python3.8/dist-packages/scrapli-2020.7.12-py3.8.egg/scrapli/driver/network_driver.py", line 392, in send_config
    multi_response = self.send_configs(
  File "/usr/local/lib/python3.8/dist-packages/scrapli-2020.7.12-py3.8.egg/scrapli/driver/network_driver.py", line 445, in send_configs
    response = super().send_command(
  File "/usr/local/lib/python3.8/dist-packages/scrapli-2020.7.12-py3.8.egg/scrapli/driver/generic_driver.py", line 75, in send_command
    raw_response, processed_response = self.channel.send_input(
  File "/usr/local/lib/python3.8/dist-packages/scrapli-2020.7.12-py3.8.egg/scrapli/channel/channel.py", line 168, in send_input
    raw_result, processed_result = self._send_input(
  File "/usr/local/lib/python3.8/dist-packages/scrapli-2020.7.12-py3.8.egg/scrapli/decorators.py", line 72, in timeout_wrapper
    result = future.get(timeout=timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/dist-packages/scrapli-2020.7.12-py3.8.egg/scrapli/channel/channel.py", line 195, in _send_input
    self._read_until_input(channel_input=bytes_channel_input)
  File "/usr/local/lib/python3.8/dist-packages/scrapli-2020.7.12-py3.8.egg/scrapli/channel/channel.py", line 82, in _read_until_input
    output += self._read_chunk()
  File "/usr/local/lib/python3.8/dist-packages/scrapli-2020.7.12-py3.8.egg/scrapli/channel/channel.py", line 47, in _read_chunk
    new_output = self.transport.read()
  File "/usr/local/lib/python3.8/dist-packages/scrapli-2020.7.12-py3.8.egg/scrapli/decorators.py", line 180, in requires_open_session_wrapper
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/scrapli-2020.7.12-py3.8.egg/scrapli/decorators.py", line 83, in timeout_wrapper
    raise ScrapliTimeout(message)
scrapli.exceptions.ScrapliTimeout: Timed out reading from transport
python@ubuntu:~/PycharmProjects/config_deploy$
```

**Comment by carlmontanari** [comment] 2020-07-19 15:48
I am starting to regret having junos be a "core" platform ![image](https://user-images.githubusercontent.com/8515611/87878181-86617500-c997-11ea-92a7-38df2a391acc.png)

I've got another "fix" for this that I'm testing. I still think this is a really bad design on the junos cli, but I'm not too upset about the fix... I'll get this pushed to develop later today -- if you could give it a test tomorrow I'd appreciate it! Thanks for sticking with me to work through this!

Carl

**Comment by ilyapetrashkevich** [comment] 2020-07-19 16:00
Haha :D 
no worries, I will test as soon as you push it to develop branch.
Thank you for helping me with it :)

**Comment by carlmontanari** [comment] 2020-07-19 16:49
updated develop branch with the fix. still doing some testing locally but I think it should be good to try!

**Comment by ilyapetrashkevich** [comment] 2020-07-19 17:18
Perfect, now it catches typo in syslog section.
Thank you very much!
When will you merge this fix with main repo?

**Comment by carlmontanari** [comment] 2020-07-19 17:24
Hopefully I'll merge/release next weekend -- I've got a few other things I'm working on I'd like to include in the next release!

**Closed** 2020-07-19 17:50 UTC
Labels: bug
