### ISSUE TITLE
switch banner config get stucked using send_configs_from_file()

### ISSUE THREAD

**Issue by GabrielSemorile** [carlmontanari/scrapli#299] opened 2023-09-11 17:01 UTC
I am using the method  send_configs_from_file() to configurate a banner for a switch but once the command `banner login ^` is entered it throws timeout (after a few seconds).

**To Reproduce**
the configuration is:

> config t
> banner login ^
> hello world
> ^
> exit
> wr

and the switch is a cisco c3560

I expect that the configuration is set as well as any other configuration command (which I already tried and worked well)

my code is:
> async def _sendConfigFromFile(self, path:str):
>   await self.connected_device.open()
>   out = await self.connected_device.send_configs_from_file(path, privilege_level="configuration")
>   return out

and the error is:
`scrapli.channel: INFO     sending channel input: config t; strip_prompt: True; eager: False
scrapli.channel: INFO     sending channel input: banner login ^; strip_prompt: True; eager: False
scrapli.channel: CRITICAL operation timed out, closing connection
asyncssh  : INFO     [conn=1] Closing connection
asyncssh  : INFO     [conn=1, chan=0] Closing channel
asyncssh  : INFO     [conn=1] Sending disconnect: Disconnected by application (11)
asyncssh  : INFO     [conn=0, chan=0] Aborting channel
asyncssh  : INFO     [conn=1] Connection closed
asyncssh  : INFO     [conn=1, chan=0] Closing channel due to connection close
asyncssh  : INFO     [conn=1, chan=0] Channel closed
asyncssh  : INFO     [conn=0] Closing connection
asyncssh  : INFO     [conn=0, chan=0] Closing channel
asyncssh  : INFO     [conn=0] Sending disconnect: Disconnected by application (11)
asyncssh  : INFO     [conn=0] Connection closed
asyncssh  : INFO     [conn=0, chan=0] Closing channel due to connection close
asyncssh  : INFO     [conn=0, chan=0] Channel closed
Traceback (most recent call last):
  File "C:\Users\gmsemor\AppData\Roaming\Python\Python39\site-packages\scrapli\channel\async_channel.py", line 491, in send_input
    buf += await self._read_until_prompt()
  File "C:\Users\gmsemor\AppData\Roaming\Python\Python39\site-packages\scrapli\channel\async_channel.py", line 137, in _read_until_prompt
    b = await self.read()
  File "C:\Users\gmsemor\AppData\Roaming\Python\Python39\site-packages\scrapli\channel\async_channel.py", line 69, in read
    buf = await self.transport.read()
  File "C:\Users\gmsemor\AppData\Roaming\Python\Python39\site-packages\scrapli\decorators.py", line 198, in decorate
    return await asyncio.wait_for(wrapped_func(*args, **kwargs), timeout=timeout)
  File "C:\Program Files\Python39\lib\asyncio\tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\asyncio\tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gmsemor\AppData\Roaming\Python\Python39\site-packages\scrapli\decorators.py", line 198, in decorate
    return await asyncio.wait_for(wrapped_func(*args, **kwargs), timeout=timeout)
  File "C:\Program Files\Python39\lib\asyncio\tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gmsemor\Desktop\dev\parametrizedSwitchConfig\singleSwitchConfig.py", line 52, in configSwitches
    output = sshHandler.sendConfigFromFile(BASECONFIGPATH)
  File "C:\Users\gmsemor\Desktop\dev\common\sshUtils.py", line 114, in sendConfigFromFile
    return asyncio.run(self._sendConfigFromFile(path))
  File "C:\Program Files\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\gmsemor\Desktop\dev\common\sshUtils.py", line 118, in _sendConfigFromFile
    out = await self.connected_device.send_configs_from_file(path, privilege_level="configuration")
  File "C:\Users\gmsemor\AppData\Roaming\Python\Python39\site-packages\scrapli\driver\network\async_driver.py", line 636, in send_configs_from_file
    return await self.send_configs(
  File "C:\Users\gmsemor\AppData\Roaming\Python\Python39\site-packages\scrapli\driver\network\async_driver.py", line 522, in send_configs
    responses = await super().send_commands(
  File "C:\Users\gmsemor\AppData\Roaming\Python\Python39\site-packages\scrapli\driver\generic\async_driver.py", line 220, in send_commands
    response = await self._send_command(
  File "C:\Users\gmsemor\AppData\Roaming\Python\Python39\site-packages\scrapli\decorators.py", line 281, in decorate
    result = await wrapped_func(*args, **kwargs)
  File "C:\Users\gmsemor\AppData\Roaming\Python\Python39\site-packages\scrapli\driver\generic\async_driver.py", line 143, in _send_command
    raw_response, processed_response = await self.channel.send_input(
  File "C:\Users\gmsemor\AppData\Roaming\Python\Python39\site-packages\scrapli\decorators.py", line 200, in decorate
    _handle_timeout(
  File "C:\Users\gmsemor\AppData\Roaming\Python\Python39\site-packages\scrapli\decorators.py", line 141, in _handle_timeout
    raise ScrapliTimeout(message)
scrapli.exceptions.ScrapliTimeout: timed out sending input to device
root      : ERROR    error:
 timed out sending input to device`

I am running this on windows 11

**Comment by carlmontanari** [comment] 2023-09-11 23:54
see [this example](https://github.com/carlmontanari/scrapli/blob/main/examples/banners_macros_etc/iosxe_banners_macros_etc.py)

I'm about to implement a thing that will make this nicer in general in scrapligo... I may try to pull it back into here as well. until then, follow that example and/or use [scraplicfg](https://github.com/scrapli/scrapli_cfg)

going to close this as this is known/expected/not a bug

**Closed by carlmontanari** 2023-09-11 23:54 UTC
Labels: bug

**Comment by GabrielSemorile** [comment] 2023-09-13 14:40
i have one more question: if i want to load many configs and only one of them is a banner, can i set eager=True for all of them (because the config file is all together) or i must separate the config and only set the eager param for the banner config?

**Comment by carlmontanari** [comment] 2023-09-13 14:48
you *can* but generally eager is not the best thing in the world. it was really added for netconf reasons then found a use for banners/macros/other stuff like that. w/ eager set we enter commands/configs, read till we see them, then hit enter (basically) and move on to the next one. with eager off (default) we then read until the prompt is seen again before continuing... hence your issue w/ the banner (no prompt at each line). 

scrapli-cfg paves over all of these issues for you basically so id say thats what id do generally.

**Comment by GabrielSemorile** [comment] 2023-09-14 13:49
i am trying to use scarpli-cfg but some errors pop up:

root      : INFO     ---------------------------------------------------- STARTING ----------------------------------------------------
scrapli   : INFO     Driver '<class 'scrapli.driver.core.cisco_iosxe.async_driver.AsyncIOSXEDriver'>' selected from scrapli core drivers
scrapli.driver: INFO     found identity file for host in ssh configuration file, using this value 'C:\Users\gmsemor/.ssh/proxy' for auth_private_key!
SSHHandler: INFO     sending configs
scrapli   : INFO     Driver '<class 'scrapli.driver.core.cisco_iosxe.async_driver.AsyncIOSXEDriver'>' selected from scrapli core drivers
scrapli.driver: INFO     found identity file for host in ssh configuration file, using this value 'C:\Users\gmsemor/.ssh/proxy' for auth_private_key!
Traceback (most recent call last):
  File "C:\Users\gmsemor\Desktop\dev\parametrizedSwitchConfig\singleSwitchConfig.py", line 53, in configSwitches
    output = sshHandler.sendConfig(config.read())
  File "C:\Users\gmsemor\Desktop\dev\common\sshUtils2.py", line 152, in sendConfig
    with AsyncScrapli(**self.device_info) as conn:
AttributeError: __enter__
root      : ERROR    error:
 __enter__
stack:
None

and my code is:
```
with AsyncScrapli(**self.device_info) as conn:
      self.config_conn = AsyncScrapliCfg(conn=conn)
```

do you have any idea what is happening here? 
thank you for helping me

**Comment by carlmontanari** [comment] 2023-09-14 15:53
probably `with AsyncScrapli` -> `async with`

but please keep issues for actual bugs. also windows is not and never will be officially supported.
